启动服务:

----
$ cd spring-cloud-config-server
$ ../mvnw spring-boot:run
----

该服务是一个Spring Boot应用程序，所以如果你喜欢你可以在你的IDE开发工具启动它(主类是`ConfigServerApplication`)。然后使用一个客户端:

----
$ curl localhost:8888/foo/development
{"name":"development","label":"master","propertySources":[
  {"name":"https://github.com/scratches/config-repo/foo-development.properties","source":{"bar":"spam"}},
  {"name":"https://github.com/scratches/config-repo/foo.properties","source":{"foo":"bar"}}
]}
----

指定属性来源默认的策略是复制Git仓库 (位置 `spring.cloud.config.server.git.uri`)并使用它初始化微型的`SpringApplication`.该微型应用程序的
`Environment`中使用枚举属性来源，并通过JSON终端发布。

HTTP服务资源格式:

----
/{application}/{profile}[/{label}]
/{application}-{profile}.yml
/{label}/{application}-{profile}.yml
/{application}-{profile}.properties
/{label}/{application}-{profile}.properties
----

这里的"application"作为`spring.config.name`注入在
`SpringApplication` (即通常"application"是一个常规的
Spring Boot应用程序), "profile"是激活配置文件 (或逗号分割属性列表), "label"是选择git分支(默认
"master".)

Spring Cloud Config Server为远程客户端从Git仓库拉取配置(必须提供):

[source,yaml]
----
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
----

=== Client Side Usage

在应用程序使用这些功能, 只是作为一个Spring
Boot应用程序依赖spring-cloud-config-client (例如查看config-client测试用例,或示例应用程序)构建.最方便的方式是添加
`org.springframework.cloud:spring-cloud-starter-config`依赖。还有一个父pom并且BOM (`spring-cloud-starter-parent`)给Maven、Gradle、Spring CLI用户提供Spring IO版本管理属性文件。Maven配置示例:

[source,xml,indent=0]
.pom.xml
----
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.3.5.RELEASE</version>
        <relativePath /> <!-- lookup parent from repository -->
    </parent>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>Brixton.RELEASE</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-config</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
		</plugins>
	</build>

    <!-- repositories also needed for snapshots and milestones -->
----

然后你可以创建一个标准的Spring Boot应用程序,像这简单的HTTP服务:

----
@SpringBootApplication
@RestController
public class Application {

    @RequestMapping("/")
    public String home() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

}
----

当它运行时，它将默认的从本地8888端口的配置服务获取外部配置，前提它是启动的.若要修改启动方式，您可以使用`bootstrap.properties` (像 `application.properties`但为应用程序上下文起引导方面作用)来修改配置服务的位置, 例如

----
spring.cloud.config.uri: http://myconfigserver.com
----

引导属性将在`/env`终端优先显示属性来源,例如

----
$ curl localhost:8080/env
{
  "profiles":[],
  "configService:https://github.com/spring-cloud-samples/config-repo/bar.properties":{"foo":"bar"},
  "servletContextInitParams":{},
  "systemProperties":{...},
  ...
}
----

(属性来源优先调用"configService:<远程仓库URL>/<文件名>" 带上"foo"属性"bar"值).

NOTE: 属性来源名字的URL是Git仓库URL并不是配置服务URL.
